+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Sun Aug 13 13:37:41 2023 - INFO  - Start environment preparation.
+ DNF_INSTALL nfs-utils
+ pkgs=nfs-utils
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs nfs-utils --node 1 --tempfile ''
Sun Aug 13 13:38:00 2023 - INFO  - pkgs:(nfs-utils) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ systemctl stop firewalld
Failed to stop firewalld.service: Unit firewalld.service not loaded.
+ iptables -F
oe_test_storage_nfs_repeat_mount.sh: line 25: iptables: command not found
+ SSH_CMD 'systemctl stop firewalld;iptables -F'
+ cmd='systemctl stop firewalld;iptables -F'
+ remoteip=
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'systemctl stop firewalld;iptables -F' -i '' -u root -p 'openEuler12#$' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Sun Aug 13 13:38:02 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ LOG_INFO 'Environmental preparation is over.'
+ message='Environmental preparation is over.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Environmental preparation is over.'
Sun Aug 13 13:38:04 2023 - INFO  - Environmental preparation is over.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase.'
+ message='Start executing testcase.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase.'
Sun Aug 13 13:38:05 2023 - INFO  - Start executing testcase.
+ SSH_CMD 'yum install nfs-utils -y;mkdir /home/nfs;touch /home/nfs/testnfs;chmod -R 777 /home/nfs;
    mv /etc/exports /etc/exports.bak;echo '\''/home/nfs *(rw,sync,all_squash)'\'' >/etc/exports'
+ cmd='yum install nfs-utils -y;mkdir /home/nfs;touch /home/nfs/testnfs;chmod -R 777 /home/nfs;
    mv /etc/exports /etc/exports.bak;echo '\''/home/nfs *(rw,sync,all_squash)'\'' >/etc/exports'
+ remoteip=
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'yum install nfs-utils -y;mkdir /home/nfs;touch /home/nfs/testnfs;chmod -R 777 /home/nfs;
    mv /etc/exports /etc/exports.bak;echo '\''/home/nfs *(rw,sync,all_squash)'\'' >/etc/exports' -i '' -u root -p 'openEuler12#$' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Sun Aug 13 13:38:07 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ SSH_CMD 'exportfs -avr'
+ cmd='exportfs -avr'
+ remoteip=
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'exportfs -avr' -i '' -u root -p 'openEuler12#$' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Sun Aug 13 13:38:09 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 35'
+ message='oe_test_storage_nfs_repeat_mount.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 35'
Sun Aug 13 13:38:11 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ SSH_CMD 'systemctl restart nfs-server rpcbind'
+ cmd='systemctl restart nfs-server rpcbind'
+ remoteip=
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'systemctl restart nfs-server rpcbind' -i '' -u root -p 'openEuler12#$' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Sun Aug 13 13:38:13 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
++ seq 1 10
+ for count_mount in $(seq 1 10)
+ mount -t nfs :/home/nfs /mnt
mount.nfs: Failed to resolve server : Name or service not known
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 41'
+ message='oe_test_storage_nfs_repeat_mount.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 41'
Sun Aug 13 13:38:23 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ df -h
+ grep
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 43'
+ message='oe_test_storage_nfs_repeat_mount.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 43'
Sun Aug 13 13:38:24 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f /mnt/testnfs
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 45'
+ message='oe_test_storage_nfs_repeat_mount.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 45'
Sun Aug 13 13:38:26 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ umount /mnt
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ for count_mount in $(seq 1 10)
+ mount -t nfs :/home/nfs /mnt
mount.nfs: Failed to resolve server : Name or service not known
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 41'
+ message='oe_test_storage_nfs_repeat_mount.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 41'
Sun Aug 13 13:38:29 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ df -h
+ grep
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 43'
+ message='oe_test_storage_nfs_repeat_mount.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 43'
Sun Aug 13 13:38:30 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f /mnt/testnfs
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 45'
+ message='oe_test_storage_nfs_repeat_mount.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 45'
Sun Aug 13 13:38:32 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ umount /mnt
umount: /mnt: not mounted.
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 47'
+ message='oe_test_storage_nfs_repeat_mount.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 47'
Sun Aug 13 13:38:34 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ for count_mount in $(seq 1 10)
+ mount -t nfs :/home/nfs /mnt
mount.nfs: Failed to resolve server : Name or service not known
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 41'
+ message='oe_test_storage_nfs_repeat_mount.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 41'
Sun Aug 13 13:38:36 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ df -h
+ grep
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 43'
+ message='oe_test_storage_nfs_repeat_mount.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 43'
Sun Aug 13 13:38:37 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f /mnt/testnfs
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 45'
+ message='oe_test_storage_nfs_repeat_mount.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 45'
Sun Aug 13 13:38:39 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ umount /mnt
umount: /mnt: not mounted.
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 47'
+ message='oe_test_storage_nfs_repeat_mount.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 47'
Sun Aug 13 13:38:41 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ for count_mount in $(seq 1 10)
+ mount -t nfs :/home/nfs /mnt
mount.nfs: Failed to resolve server : Name or service not known
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 41'
+ message='oe_test_storage_nfs_repeat_mount.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 41'
Sun Aug 13 13:38:43 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ df -h
+ grep
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 43'
+ message='oe_test_storage_nfs_repeat_mount.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 43'
Sun Aug 13 13:38:44 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f /mnt/testnfs
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 45'
+ message='oe_test_storage_nfs_repeat_mount.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 45'
Sun Aug 13 13:38:46 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ umount /mnt
umount: /mnt: not mounted.
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 47'
+ message='oe_test_storage_nfs_repeat_mount.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 47'
Sun Aug 13 13:38:48 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ for count_mount in $(seq 1 10)
+ mount -t nfs :/home/nfs /mnt
mount.nfs: Failed to resolve server : Name or service not known
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 41'
+ message='oe_test_storage_nfs_repeat_mount.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 41'
Sun Aug 13 13:38:50 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ df -h
+ grep
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 43'
+ message='oe_test_storage_nfs_repeat_mount.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 43'
Sun Aug 13 13:38:51 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f /mnt/testnfs
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 45'
+ message='oe_test_storage_nfs_repeat_mount.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 45'
Sun Aug 13 13:38:53 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ umount /mnt
umount: /mnt: not mounted.
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 47'
+ message='oe_test_storage_nfs_repeat_mount.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 47'
Sun Aug 13 13:38:55 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ for count_mount in $(seq 1 10)
+ mount -t nfs :/home/nfs /mnt
mount.nfs: Failed to resolve server : Name or service not known
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 41'
+ message='oe_test_storage_nfs_repeat_mount.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 41'
Sun Aug 13 13:38:56 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ df -h
+ grep
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 43'
+ message='oe_test_storage_nfs_repeat_mount.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 43'
Sun Aug 13 13:38:58 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f /mnt/testnfs
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 45'
+ message='oe_test_storage_nfs_repeat_mount.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 45'
Sun Aug 13 13:39:00 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ umount /mnt
umount: /mnt: not mounted.
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 47'
+ message='oe_test_storage_nfs_repeat_mount.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 47'
Sun Aug 13 13:39:01 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ for count_mount in $(seq 1 10)
+ mount -t nfs :/home/nfs /mnt
mount.nfs: Failed to resolve server : Name or service not known
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 41'
+ message='oe_test_storage_nfs_repeat_mount.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 41'
Sun Aug 13 13:39:03 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ df -h
+ grep
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 43'
+ message='oe_test_storage_nfs_repeat_mount.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 43'
Sun Aug 13 13:39:05 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f /mnt/testnfs
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 45'
+ message='oe_test_storage_nfs_repeat_mount.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 45'
Sun Aug 13 13:39:06 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ umount /mnt
umount: /mnt: not mounted.
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 47'
+ message='oe_test_storage_nfs_repeat_mount.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 47'
Sun Aug 13 13:39:08 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ for count_mount in $(seq 1 10)
+ mount -t nfs :/home/nfs /mnt
mount.nfs: Failed to resolve server : Name or service not known
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 41'
+ message='oe_test_storage_nfs_repeat_mount.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 41'
Sun Aug 13 13:39:10 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ df -h
+ grep
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 43'
+ message='oe_test_storage_nfs_repeat_mount.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 43'
Sun Aug 13 13:39:12 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f /mnt/testnfs
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 45'
+ message='oe_test_storage_nfs_repeat_mount.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 45'
Sun Aug 13 13:39:13 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ umount /mnt
umount: /mnt: not mounted.
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 47'
+ message='oe_test_storage_nfs_repeat_mount.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 47'
Sun Aug 13 13:39:15 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ for count_mount in $(seq 1 10)
+ mount -t nfs :/home/nfs /mnt
mount.nfs: Failed to resolve server : Name or service not known
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 41'
+ message='oe_test_storage_nfs_repeat_mount.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 41'
Sun Aug 13 13:39:17 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ df -h
+ grep
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 43'
+ message='oe_test_storage_nfs_repeat_mount.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 43'
Sun Aug 13 13:39:19 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f /mnt/testnfs
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 45'
+ message='oe_test_storage_nfs_repeat_mount.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 45'
Sun Aug 13 13:39:20 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ umount /mnt
umount: /mnt: not mounted.
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 47'
+ message='oe_test_storage_nfs_repeat_mount.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 47'
Sun Aug 13 13:39:22 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ for count_mount in $(seq 1 10)
+ mount -t nfs :/home/nfs /mnt
mount.nfs: Failed to resolve server : Name or service not known
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 41'
+ message='oe_test_storage_nfs_repeat_mount.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 41'
Sun Aug 13 13:39:24 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ df -h
+ grep
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
+ CHECK_RESULT 2
+ actual_result=2
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 0 -eq 0 ']'
+ test 2x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 43'
+ message='oe_test_storage_nfs_repeat_mount.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 43'
Sun Aug 13 13:39:26 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f /mnt/testnfs
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 45'
+ message='oe_test_storage_nfs_repeat_mount.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 45'
Sun Aug 13 13:39:27 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ umount /mnt
umount: /mnt: not mounted.
+ CHECK_RESULT 32
+ actual_result=32
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 32 ']'
+ '[' 0 -eq 0 ']'
+ test 32x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_nfs_repeat_mount.sh line 47'
+ message='oe_test_storage_nfs_repeat_mount.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_nfs_repeat_mount.sh line 47'
Sun Aug 13 13:39:29 2023 - ERROR - oe_test_storage_nfs_repeat_mount.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End of testcase execution.'
+ message='End of testcase execution.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of testcase execution.'
Sun Aug 13 13:39:31 2023 - INFO  - End of testcase execution.
+ CASE_RESULT 0
+ case_re=0
+ test -z 40
+ test 40 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sun Aug 13 13:39:32 2023 - ERROR - failed to execute the case.
+ exit 40
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Sun Aug 13 13:39:34 2023 - INFO  - start environment cleanup.
+ SSH_CMD 'rm -rf /home/nfs;yum remove -y nfs-utils;mv -f /etc/exports.bak /etc/exports'
+ cmd='rm -rf /home/nfs;yum remove -y nfs-utils;mv -f /etc/exports.bak /etc/exports'
+ remoteip=
+ remotepasswd='openEuler12#$'
+ remoteuser=root
+ timeout=300
+ connport=22
+ bash /root/mugen/libs/locallibs/sshcmd.sh -c 'rm -rf /home/nfs;yum remove -y nfs-utils;mv -f /etc/exports.bak /etc/exports' -i '' -u root -p 'openEuler12#$' -t 300 -o 22
Usage: sshcmd.sh -c "command" -i "remote machinet ip" [-u login_user] [-p login_password] [-o port] [-t timeout]+ ret=1
+ test 1 -ne 0
+ LOG_ERROR 'Failed in remote CMD operation:1'
+ message='Failed in remote CMD operation:1'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote CMD operation:1'
Sun Aug 13 13:39:36 2023 - ERROR - Failed in remote CMD operation:1
+ return 1
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Sun Aug 13 13:39:37 2023 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Sun Aug 13 13:39:39 2023 - INFO  - Finish environment cleanup.
