+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Thu Oct 19 22:29:55 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL 'aide gcc'
+ pkgs='aide gcc'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'aide gcc' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpfke5mi8r
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpfke5mi8r
+ sed -i '$a/home DATAONLY' /etc/aide.conf
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Thu Oct 19 22:31:05 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Thu Oct 19 22:31:05 2023 - INFO  - Start to run test.
+ aide --init
Start timestamp: 2023-10-19 22:31:05 +0800 (AIDE 0.18.5)
AIDE successfully initialized database.
New AIDE database written to /var/lib/aide/aide.db.new.gz

Number of entries:	61392

---------------------------------------------------
The attributes of the (uncompressed) database(s):
---------------------------------------------------

/var/lib/aide/aide.db.new.gz
 MD5       : 0NBA62Hh8S9qsEcUff7RiQ==
 SHA1      : wGVfr0IYvDmdyfrGaFjvE0FFv7g=
 SHA256    : 8iDMM7R2OW6kXqqU7bVWBHp+iHTBvO1W
             Hwbth4oJF30=
 SHA512    : iTjcuFjGt1R3R6YvxkOdgFuAMpPU/P1p
             +W6QqEhD9eVKpjjh3FHc1OpnNHZWcgxX
             3jw1jvkWiad6d+xlJNLICQ==
 RMD160    : 1EsAfqceLxH0XRsPuiWtL4/Di2s=
 TIGER     : np/F07Ovz62CsZ9ANJHmSsLiwxDJHJuj
 CRC32     : Ohhtgg==
 WHIRLPOOL : OBQN/OmWCRydZQ8ZT2WN47aBMgS5+qI4
             yBXkIwv3Ethr2zAbKetoxSasUBsaLzAH
             /dqJs1HVjyI6zQ8xBZGMZg==
 GOST      : JGljmwU3qzya3Ovap/PqrHPogIu84Q0c
             Z1ucT9hZShc=
 STRIBOG256: T0iNMc3Xtc8NKrlHeiOQ7uWC8ROZPRon
             4UV7M7fyjoI=
 STRIBOG512: +rbdO/JRldN5HeOphHSo06syxdJaDZP0
             cF/fYnVeg1Jkpk4pA18+x+ADnJmvqV6r
             hQyKrVHhBj7xVCaorMWEOg==
 SM3       : GN1cUckT1/ous9OboLOSqvWDjboNEfG5
             sNn7lKM6QFs=


End timestamp: 2023-10-19 22:35:55 +0800 (run time: 4m 50s)
+ CHECK_RESULT 0 0 0 'initialization failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='initialization failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
+ useradd testuser
+ aide -c /etc/aide.conf --update
+ grep -A 10 'Changed entries:'
+ grep /etc/group
f > ... mci.H..  : /etc/group
f < ... mc..H..  : /etc/group-
+ CHECK_RESULT 0 0 0 'Update execution failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Update execution failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ test -f /var/lib/aide/aide.db.new.gz
+ CHECK_RESULT 0 0 0 'Update execution failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Update execution failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
+ aide --check
+ grep Changed entries:
grep: entries:: No such file or directory
WARNING: hash calculation: '/etc/localtime_tmp' has been changed (changed attributes: c+m, hash could not be calculated)
WARNING: hash calculation: '/root/mugen/logs/smoke-basic-os/oe_test_aide_update_database/2023-10-19-22:29:53.log' has been changed (changed attributes: s+c+m, hash could not be calculated)
+ CHECK_RESULT 2 0 1 'Check execution failed'
+ actual_result=2
+ expect_result=0
+ mode=1
+ error_log='Check execution failed'
+ exit_mode=0
+ '[' -z 2 ']'
+ '[' 1 -eq 0 ']'
+ test 2x == 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Thu Oct 19 22:49:18 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z ''
+ test 0 -eq 0
+ LOG_INFO 'succeed to execute the case.'
+ message='succeed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'succeed to execute the case.'
Thu Oct 19 22:49:19 2023 - INFO  - succeed to execute the case.
+ exec_result=
+ exit 0
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Thu Oct 19 22:49:19 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpfke5mi8r ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpfke5mi8r
+ '[' 0 -ne 0 ']'
+ userdel -rf testuser
+ rm -rf testlog /var/log/aide/aide.log /var/lib/aide/aide.db.gz
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Thu Oct 19 22:49:34 2023 - INFO  - End to restore the test environment.
