+ source ./common/disk_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment!'
+ message='Start to prepare the test environment!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment!'
Wed Oct 11 11:13:33 2023 - INFO  - Start to prepare the test environment!
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/mugen/libs/locallibs/get_test_device.py --device disk --node 1
+ disks='vdb vdc'
+ disk_list=($disks)
+ local_disk=vdb
+ local_disk1=vdc
+ local_disk2=
+ local_disk3=
+ DNF_INSTALL fio
+ pkgs=fio
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs fio --node 1 --tempfile ''
Wed Oct 11 11:14:22 2023 - INFO  - pkgs:(fio) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ echo dsafdsfdddddddddddddddddddddddddddddddddddddddddd
+ LOG_INFO 'End to prepare the test environment!'
+ message='End to prepare the test environment!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment!'
Wed Oct 11 11:14:23 2023 - INFO  - End to prepare the test environment!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Wed Oct 11 11:14:23 2023 - INFO  - Start executing testcase!
+ fio-dedupe -o 1 /dev/vdb
+ grep 'Will check </dev/vdb>'
Will check </dev/vdb>, size <2147483648>, using 4 threads
+ CHECK_RESULT 0 0 0 'check disk failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='check disk failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ fio-dedupe -c 1 /dev/vdb
oe_test_fio_003.sh: line 32: fio-dedupe: command not found
+ grep 'Will check </dev/vdb>'
+ CHECK_RESULT 1 0 0 'check disk failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='check disk failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'check disk failed'
+ LOG_ERROR 'check disk failed'
+ message='check disk failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'check disk failed'
Wed Oct 11 11:14:30 2023 - ERROR - check disk failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fio_003.sh line 33'
+ message='oe_test_fio_003.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fio_003.sh line 33'
Wed Oct 11 11:14:31 2023 - ERROR - oe_test_fio_003.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ fio-dedupe -B 1 /dev/vdb
oe_test_fio_003.sh: line 34: fio-dedupe: command not found
+ grep 'Will check </dev/vdb>'
+ CHECK_RESULT 1 0 0 'check disk failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='check disk failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'check disk failed'
+ LOG_ERROR 'check disk failed'
+ message='check disk failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'check disk failed'
Wed Oct 11 11:14:32 2023 - ERROR - check disk failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fio_003.sh line 35'
+ message='oe_test_fio_003.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fio_003.sh line 35'
Wed Oct 11 11:14:32 2023 - ERROR - oe_test_fio_003.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ fio-dedupe -p 1 /dev/vdb
oe_test_fio_003.sh: line 36: fio-dedupe: command not found
+ grep 'Will check </dev/vdb>'
+ CHECK_RESULT 1 0 0 'check disk failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='check disk failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'check disk failed'
+ LOG_ERROR 'check disk failed'
+ message='check disk failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'check disk failed'
Wed Oct 11 11:14:33 2023 - ERROR - check disk failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fio_003.sh line 37'
+ message='oe_test_fio_003.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fio_003.sh line 37'
Wed Oct 11 11:14:34 2023 - ERROR - oe_test_fio_003.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ fio --filename=test_file --direct=1 --rw=randwrite --numjobs=1 --iodepth=16 --ioengine=libaio --bs=4k --group_reporting --name=zhangyi --log_avg_msec=500 --write_bw_log=test-fio --size=1G
oe_test_fio_003.sh: line 38: fio: command not found
+ grep 'Starting 1 process'
+ CHECK_RESULT 1 0 0 'fio --filename=test_file option failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='fio --filename=test_file option failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'fio --filename=test_file option failed'
+ LOG_ERROR 'fio --filename=test_file option failed'
+ message='fio --filename=test_file option failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'fio --filename=test_file option failed'
Wed Oct 11 11:14:34 2023 - ERROR - fio --filename=test_file option failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fio_003.sh line 39'
+ message='oe_test_fio_003.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fio_003.sh line 39'
Wed Oct 11 11:14:35 2023 - ERROR - oe_test_fio_003.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ fio -filename=/dev/vdb -direct=1 -iodepth 1 -thread -rw=read -ioengine=psync -bs=16k -size=200G -numjobs=30 -runtime=1000 -group_reporting -name=mytest
+ grep vdb
oe_test_fio_003.sh: line 40: fio: command not found
+ CHECK_RESULT 1 0 0 'fio --filename=test_file option failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='fio --filename=test_file option failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'fio --filename=test_file option failed'
+ LOG_ERROR 'fio --filename=test_file option failed'
+ message='fio --filename=test_file option failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'fio --filename=test_file option failed'
Wed Oct 11 11:14:36 2023 - ERROR - fio --filename=test_file option failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fio_003.sh line 41'
+ message='oe_test_fio_003.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fio_003.sh line 41'
Wed Oct 11 11:14:37 2023 - ERROR - oe_test_fio_003.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ fio -filename=/dev/vdb -direct=1 -iodepth 1 -thread -rw=write -ioengine=psync -bs=16k -size=200G -numjobs=30 -runtime=1000 -group_reporting -name=mytest
oe_test_fio_003.sh: line 42: fio: command not found
+ grep vdb
+ CHECK_RESULT 1 0 0 'fio --filename=test_file option failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='fio --filename=test_file option failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'fio --filename=test_file option failed'
+ LOG_ERROR 'fio --filename=test_file option failed'
+ message='fio --filename=test_file option failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'fio --filename=test_file option failed'
Wed Oct 11 11:14:37 2023 - ERROR - fio --filename=test_file option failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fio_003.sh line 43'
+ message='oe_test_fio_003.sh line 43'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fio_003.sh line 43'
Wed Oct 11 11:14:38 2023 - ERROR - oe_test_fio_003.sh line 43
+ '[' 0 -eq 1 ']'
+ return 0
+ fio -filename=/dev/vdb -direct=1 -iodepth 1 -thread -rw=randread -ioengine=psync -bs=16k -size=200G -numjobs=30 -runtime=1000 -group_reporting -name=mytest
oe_test_fio_003.sh: line 44: fio: command not found
+ grep vdb
+ CHECK_RESULT 1 0 0 'fio --filename=test_file option failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='fio --filename=test_file option failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'fio --filename=test_file option failed'
+ LOG_ERROR 'fio --filename=test_file option failed'
+ message='fio --filename=test_file option failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'fio --filename=test_file option failed'
Wed Oct 11 11:14:39 2023 - ERROR - fio --filename=test_file option failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fio_003.sh line 45'
+ message='oe_test_fio_003.sh line 45'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fio_003.sh line 45'
Wed Oct 11 11:14:40 2023 - ERROR - oe_test_fio_003.sh line 45
+ '[' 0 -eq 1 ']'
+ return 0
+ fio -filename=/dev/vdb -direct=1 -iodepth 1 -thread -rw=randwrite -ioengine=psync -bs=16k -size=200G -numjobs=30 -runtime=1000 -group_reporting -name=mytest
oe_test_fio_003.sh: line 46: fio: command not found
+ grep vdb
+ CHECK_RESULT 1 0 0 'fio --filename=test_file option failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='fio --filename=test_file option failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'fio --filename=test_file option failed'
+ LOG_ERROR 'fio --filename=test_file option failed'
+ message='fio --filename=test_file option failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'fio --filename=test_file option failed'
Wed Oct 11 11:14:40 2023 - ERROR - fio --filename=test_file option failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fio_003.sh line 47'
+ message='oe_test_fio_003.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fio_003.sh line 47'
Wed Oct 11 11:14:41 2023 - ERROR - oe_test_fio_003.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ fio -filename=/dev/vdb -direct=1 -iodepth 1 -thread -rw=read -ioengine=psync -bs=16k -size=200G -numjobs=30 -runtime=1000 -group_reporting -name=mytest --output test.txt
oe_test_fio_003.sh: line 48: fio: command not found
+ test -f ./test_file
+ CHECK_RESULT 1 0 0 'fio --filename=test_file option failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='fio --filename=test_file option failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'fio --filename=test_file option failed'
+ LOG_ERROR 'fio --filename=test_file option failed'
+ message='fio --filename=test_file option failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'fio --filename=test_file option failed'
Wed Oct 11 11:14:41 2023 - ERROR - fio --filename=test_file option failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fio_003.sh line 50'
+ message='oe_test_fio_003.sh line 50'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fio_003.sh line 50'
Wed Oct 11 11:14:42 2023 - ERROR - oe_test_fio_003.sh line 50
+ '[' 0 -eq 1 ']'
+ return 0
+ genfio -d /dev/vdb,/dev/vdc,/dev/ -a -b 4k,128k,1m -r 100 -a -x dellr720-day2/
oe_test_fio_003.sh: line 51: genfio: command not found
+ test -d dellr720-day2
+ CHECK_RESULT 1 0 0 'fio --filename=test_file option failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='fio --filename=test_file option failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'fio --filename=test_file option failed'
+ LOG_ERROR 'fio --filename=test_file option failed'
+ message='fio --filename=test_file option failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'fio --filename=test_file option failed'
Wed Oct 11 11:14:43 2023 - ERROR - fio --filename=test_file option failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_fio_003.sh line 53'
+ message='oe_test_fio_003.sh line 53'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_fio_003.sh line 53'
Wed Oct 11 11:14:44 2023 - ERROR - oe_test_fio_003.sh line 53
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End of testcase execution!'
+ message='End of testcase execution!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of testcase execution!'
Wed Oct 11 11:14:44 2023 - INFO  - End of testcase execution!
+ CASE_RESULT 0
+ case_re=0
+ test -z 10
+ test 10 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Oct 11 11:14:45 2023 - ERROR - failed to execute the case.
+ exit 10
+ post_test
+ LOG_INFO 'Start environment cleanup.'
+ message='Start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment cleanup.'
Wed Oct 11 11:14:46 2023 - INFO  - Start environment cleanup.
+ rm -rf test_file test.txt test-fio_bw.1.log dellr720-day2
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Wed Oct 11 11:14:46 2023 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Wed Oct 11 11:14:47 2023 - INFO  - Finish environment cleanup.
