+ source ../common/storage_disk_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Sun Aug 13 12:13:59 2023 - INFO  - Start environment preparation.
+ check_free_disk 2
++ TEST_DISK
++ id=1
++ python3 /root/mugen/libs/locallibs/get_test_device.py --device disk --node 1
+ disks=
+ disk_list=($disks)
+ local_disk=
+ local_disk1=
+ local_disk2=
+ local_disk3=
+ mkfs.ext4 -F /dev/
mke2fs 1.46.5 (30-Dec-2021)
mkfs.ext4: Device size reported to be zero.  Invalid partition specified, or
	partition table wasn't reread after running fdisk, due to
	a modified partition being busy and in use.  You may need to reboot
	to re-read your partition table.

+ mkfs.ext4 -F /dev/
mke2fs 1.46.5 (30-Dec-2021)
mkfs.ext4: Device size reported to be zero.  Invalid partition specified, or
	partition table wasn't reread after running fdisk, due to
	a modified partition being busy and in use.  You may need to reboot
	to re-read your partition table.

+ pvcreate -y /dev/ /dev/
  No device found for /dev/.
  No device found for /dev/.
+ vgcreate openeulertest /dev/ /dev/
  No device found for /dev/.
  No device found for /dev/.
+ lvcreate -L 200M -n test openeulertest --persistent y --major 253 --minor 7788 -y
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
++ pvs -o+pv_used
++ wc -l
+ number=0
+ LOG_INFO 'Environmental preparation is over.'
+ message='Environmental preparation is over.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Environmental preparation is over.'
Sun Aug 13 12:14:11 2023 - INFO  - Environmental preparation is over.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Sun Aug 13 12:14:13 2023 - INFO  - Start executing testcase!
+ test 0 -gt 3
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_set_label.sh line 35'
+ message='oe_test_storage_lvm_set_label.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_set_label.sh line 35'
Sun Aug 13 12:14:14 2023 - ERROR - oe_test_storage_lvm_set_label.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ lvchange --persistent y --major 253 --minor 7788 openeulertest/test -y
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_set_label.sh line 37'
+ message='oe_test_storage_lvm_set_label.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_set_label.sh line 37'
Sun Aug 13 12:14:16 2023 - ERROR - oe_test_storage_lvm_set_label.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End of testcase execution!'
+ message='End of testcase execution!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of testcase execution!'
Sun Aug 13 12:14:18 2023 - INFO  - End of testcase execution!
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sun Aug 13 12:14:19 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Sun Aug 13 12:14:21 2023 - INFO  - start environment cleanup.
+ lvremove openeulertest/test -y
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ vgremove openeulertest -y
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ pvremove /dev/ /dev/ -y
  No device found for /dev/.
  No device found for /dev/.
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Sun Aug 13 12:14:24 2023 - INFO  - Finish environment cleanup.
