+ source ../common_lib/fsio_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 0 -eq 0 ]]
+++ lsblk
+++ grep test_vggroup
+++ awk '{print $1}'
+++ head -n 1
+++ cut -d - -f 1
++ vggroup=└─test_vggroup20230809022303
++ vggroup=test_vggroup20230809022303
++ vgremove test_vggroup20230809022303 -y
  Logical volume "test_lv20230809022357" successfully removed.
  Volume group "test_vggroup20230809022303" successfully removed
++ rm -rf '/tmp/point*'
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Wed Aug  9 02:24:26 2023 - INFO  - Start to prepare the database config.
++ date +%Y%m%d%H%M%S
+ cur_date=20230809022426
++ CREATE_VG
+++ date +%Y%m%d%H%M%S
++ cur_date=20230809022426
+++ lsblk
+++ grep disk
+++ awk '{print $1}'
+++ tail -n 1
++ free_disk=vdb
++ disk_name=/dev/vdb
++ pvcreate /dev/vdb -f
++ [[ 0 -eq 0 ]]
++ vggroup=test_vggroup20230809022426
++ vgcreate test_vggroup20230809022426 /dev/vdb
++ printf test_vggroup20230809022426
+ vggroup=test_vggroup20230809022426
+ lv=test_lv20230809022426
+ lvcreate -n test_lv20230809022426 -L 2G test_vggroup20230809022426 -y
+ mkfs.ext3 /dev/test_vggroup20230809022426/test_lv20230809022426
mke2fs 1.47.0 (5-Feb-2023)
Discarding device blocks:      0/524288             done                            
Creating filesystem with 524288 4k blocks and 131072 inodes
Filesystem UUID: 6f140420-3764-43b5-b808-99e289100822
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912

Allocating group tables:  0/16     done                            
Writing inode tables:  0/16     done                            
Creating journal (16384 blocks): done
Writing superblocks and filesystem accounting information:  0/16     done

+ ext3_point=/mnt/test20230809022426
+ mkdir /mnt/test20230809022426
+ data=('remount-ro' 'continue' 'panic')
+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Wed Aug  9 02:24:32 2023 - INFO  - Finish to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Wed Aug  9 02:24:34 2023 - INFO  - Start to run test.
+ for var in ${data[@]}
+ mount -t ext3 -o errors=remount-ro /dev/test_vggroup20230809022426/test_lv20230809022426 /mnt/test20230809022426
+ CHECK_RESULT 0 0 0 'Mount ext3 by errors=remount-ro failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Mount ext3 by errors=remount-ro failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount -f /dev/test_vggroup20230809022426/test_lv20230809022426
+ for var in ${data[@]}
+ mount -t ext3 -o errors=continue /dev/test_vggroup20230809022426/test_lv20230809022426 /mnt/test20230809022426
+ CHECK_RESULT 0 0 0 'Mount ext3 by errors=continue failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Mount ext3 by errors=continue failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount -f /dev/test_vggroup20230809022426/test_lv20230809022426
+ for var in ${data[@]}
+ mount -t ext3 -o errors=panic /dev/test_vggroup20230809022426/test_lv20230809022426 /mnt/test20230809022426
+ CHECK_RESULT 0 0 0 'Mount ext3 by errors=panic failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Mount ext3 by errors=panic failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ umount -f /dev/test_vggroup20230809022426/test_lv20230809022426
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Wed Aug  9 02:24:35 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z ''
+ test 0 -eq 0
+ LOG_INFO 'succeed to execute the case.'
+ message='succeed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'succeed to execute the case.'
Wed Aug  9 02:24:36 2023 - INFO  - succeed to execute the case.
+ exec_result=
+ exit 0
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Wed Aug  9 02:24:37 2023 - INFO  - Start to restore the test environment.
+ rm -rf /mnt/test20230809022426
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Wed Aug  9 02:24:38 2023 - INFO  - End to restore the test environment.
