+ source ../common/storage_disk_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test env'
+ message='Start to prepare the test env'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test env'
Sun Aug 13 15:15:52 2023 - INFO  - Start to prepare the test env
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/mugen/libs/locallibs/get_test_device.py --device disk --node 1
+ disks=
+ disk_list=($disks)
+ local_disk=
+ local_disk1=
+ local_disk2=
+ local_disk3=
+ pvcreate -y /dev/
  No device found for /dev/.
+ vgcreate openeulertest /dev/
  No device found for /dev/.
+ lvcreate -y -L 50MB -n test openeulertest /dev/
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ LOG_INFO 'End to prepare the test env'
+ message='End to prepare the test env'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test env'
Sun Aug 13 15:16:03 2023 - INFO  - End to prepare the test env
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Sun Aug 13 15:16:05 2023 - INFO  - Start executing testcase!
+ lvchange -an openeulertest/test
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_activation.sh line 32'
+ message='oe_test_storage_lvm_activation.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_activation.sh line 32'
Sun Aug 13 15:16:07 2023 - ERROR - oe_test_storage_lvm_activation.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ lvchange -ay openeulertest/test
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_activation.sh line 34'
+ message='oe_test_storage_lvm_activation.sh line 34'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_activation.sh line 34'
Sun Aug 13 15:16:09 2023 - ERROR - oe_test_storage_lvm_activation.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
+ lvchange -an openeulertest
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_activation.sh line 36'
+ message='oe_test_storage_lvm_activation.sh line 36'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_activation.sh line 36'
Sun Aug 13 15:16:11 2023 - ERROR - oe_test_storage_lvm_activation.sh line 36
+ '[' 0 -eq 1 ']'
+ return 0
+ lvchange -ay openeulertest
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_activation.sh line 38'
+ message='oe_test_storage_lvm_activation.sh line 38'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_activation.sh line 38'
Sun Aug 13 15:16:13 2023 - ERROR - oe_test_storage_lvm_activation.sh line 38
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End of testcase execution!'
+ message='End of testcase execution!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of testcase execution!'
Sun Aug 13 15:16:14 2023 - INFO  - End of testcase execution!
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Sun Aug 13 15:16:15 2023 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Sun Aug 13 15:16:17 2023 - INFO  - start environment cleanup.
+ vgremove -y openeulertest
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ pvremove /dev/
  No device found for /dev/.
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Sun Aug 13 15:16:19 2023 - INFO  - Finish environment cleanup.
