+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Thu Sep 21 21:17:41 2023 - INFO  - Start environmental preparation.
+ DNF_INSTALL 'libreswan net-tools'
+ pkgs='libreswan net-tools'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'libreswan net-tools' --node 1 --tempfile ''
Thu Sep 21 21:17:54 2023 - INFO  - pkgs:(libreswan net-tools) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ DNF_INSTALL 'libreswan net-tools' 2
+ pkgs='libreswan net-tools'
+ node=2
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'libreswan net-tools' --node 2 --tempfile ''
Traceback (most recent call last):
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 187, in <module>
    exitcode, output = rpm_install(args.pkgs, args.node, args.tempfile)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 66, in rpm_install
    conn = ssh_cmd.pssh_conn(
           ^^^^^^^^^^^^^^^^^^
  File "/root/mugen/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 377, in connect
    to_try = list(self._families_and_addresses(hostname, port))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 202, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ systemctl start firewalld
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Thu Sep 21 21:17:57 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase.'
+ message='Start executing testcase.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase.'
Thu Sep 21 21:17:58 2023 - INFO  - Start executing testcase.
+ systemctl enable ipsec --now
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ grep success
+ firewall-cmd --add-service=ipsec
success
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ firewall-cmd --runtime-to-permanent
+ grep success
success
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
++ ipsec newhostkey --nssdir /etc/ipsec.d/
++ awk '/Generated/{print $7}'
+ left_ckaid=bdb025022f16b1fcafc5e25418ef05cdb01e2b69
++ ifconfig
++ grep netmask
++ tr -s ' '
++ awk '{print $4}'
+ left_mask='255.255.0.0
255.255.255.0
255.0.0.0'
++ ip -6 route show dev
++ head -n 1
++ awk '{print $1}'
Command line is not complete. Try option "help"
+ left6_mask=
++ ipsec showhostkey --left --ckaid bdb025022f16b1fcafc5e25418ef05cdb01e2b69 --nssdir /etc/ipsec.d/
++ grep leftrsasigkey
++ awk -F leftrsasigkey= '{print $2}'
++ sed 's/^[ \t]*//g'
+ left_rsa=0sAwEAAcdalcYYecvYjDPVK2QB8w+6poWzRVRZP6++oV3TPqJHMNs7ePvaPbMCgmxMkTu8mVgmFBh3TidZQIgsP3TNJJCvqef7kMH1hRvuGO0QR55EW8GTrpz7dra8Somu7UNpH5PtrMxPw3rFnocMfApiQY7BJ3qEKDdNz2x7OmCsLyMtQD6wXOfKPLFEDInnELc+NvII1Mg1Re3F7QZLQjQbB0fZXrWMwiz3ONGEYqcyi1t9B2kBjvvpnbyfF03SjdHDnqZXvr8J+C7AVoktCPFx/qAAdEC1c3hq0m4Ilig8LMr3F4Z1rE4JN1UvFgxH3LMw2GagAEi5P88K3NlZJDnkG6+CzZFKdz0qBdUmq3N10yHkuQaw/41B3Lj6Wxn/rtUH5RutU368AY+R6xubTxzFouid+G0gVNjsRIwg8VGooCNo9PS1jn1CfeMPKszCTUS2Wlg5J3kBB1HI4F1K7XwVLiUKeNbWMGnb9FI5Wrn8uwlPa2lpNmgGJB+G2ZZKMUAmy00nHb9swEI8XBmdDNNLb15Vye7ENssV2uK0J777LXtJPKr7hLNECFtvyzdo0PEIUgGj0Ky1klj2PwUoT40zTaobU/UP+VU=
+ P_SSH_CMD --cmd 'systemctl start firewalld;systemctl enable ipsec --now' --node 2
+ python3 /root/mugen/libs/locallibs/ssh_cmd.py --cmd 'systemctl start firewalld;systemctl enable ipsec --now' --node 2
Thu Sep 21 21:18:27 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_site_to_site_vpn.sh line 44'
+ message='oe_test_site_to_site_vpn.sh line 44'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_site_to_site_vpn.sh line 44'
Thu Sep 21 21:18:27 2023 - ERROR - oe_test_site_to_site_vpn.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ P_SSH_CMD --cmd 'firewall-cmd --add-service=\"ipsec\";firewall-cmd --runtime-to-permanent' --node 2
+ python3 /root/mugen/libs/locallibs/ssh_cmd.py --cmd 'firewall-cmd --add-service=\"ipsec\";firewall-cmd --runtime-to-permanent' --node 2
Thu Sep 21 21:18:30 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_site_to_site_vpn.sh line 46'
+ message='oe_test_site_to_site_vpn.sh line 46'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_site_to_site_vpn.sh line 46'
Thu Sep 21 21:18:30 2023 - ERROR - oe_test_site_to_site_vpn.sh line 46
+ '[' 0 -eq 1 ']'
+ return 0
+ P_SSH_CMD --cmd 'ipsec newhostkey --nssdir /etc/ipsec.d/ 2>&1 | grep Generated | cut -d '\'' '\'' -f 7 >/tmp/key.txt' --node 2
+ python3 /root/mugen/libs/locallibs/ssh_cmd.py --cmd 'ipsec newhostkey --nssdir /etc/ipsec.d/ 2>&1 | grep Generated | cut -d '\'' '\'' -f 7 >/tmp/key.txt' --node 2
Thu Sep 21 21:18:33 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ SSH_SCP @:/tmp/key.txt /tmp
+ src=@:/tmp/key.txt
+ dest=/tmp
+ remotepasswd='openEuler12#$'
+ connport=22
+ bash /root/mugen/libs/locallibs/sshscp.sh -p 'openEuler12#$' -o 22 -s @:/tmp/key.txt -d /tmp
Thu Sep 21 21:18:33 2023 - WARN  - the remote password uses the default configuration.
Thu Sep 21 21:18:34 2023 - WARN  - the connect port using the default configuration
spawn scp -P 22 -r @:/tmp/key.txt /tmp
ssh: Could not resolve hostname : Name or service not known
scp: Connection closed
+ ret=255
+ test 255 -ne 0
+ LOG_ERROR 'Failed in remote SCP operation: 255'
+ message='Failed in remote SCP operation: 255'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote SCP operation: 255'
Thu Sep 21 21:18:35 2023 - ERROR - Failed in remote SCP operation: 255
+ return 255
++ cat /tmp/key.txt
cat: /tmp/key.txt: No such file or directory
+ right_ckaid=
+ P_SSH_CMD --cmd 'ipsec showhostkey --right --ckaid  --nssdir /etc/ipsec.d/  | grep rightrsasigkey > /tmp/rsa.txt' --node 2
+ python3 /root/mugen/libs/locallibs/ssh_cmd.py --cmd 'ipsec showhostkey --right --ckaid  --nssdir /etc/ipsec.d/  | grep rightrsasigkey > /tmp/rsa.txt' --node 2
Thu Sep 21 21:18:38 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_site_to_site_vpn.sh line 52'
+ message='oe_test_site_to_site_vpn.sh line 52'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_site_to_site_vpn.sh line 52'
Thu Sep 21 21:18:38 2023 - ERROR - oe_test_site_to_site_vpn.sh line 52
+ '[' 0 -eq 1 ']'
+ return 0
+ SSH_SCP @:/tmp/rsa.txt /tmp
+ src=@:/tmp/rsa.txt
+ dest=/tmp
+ remotepasswd='openEuler12#$'
+ connport=22
+ bash /root/mugen/libs/locallibs/sshscp.sh -p 'openEuler12#$' -o 22 -s @:/tmp/rsa.txt -d /tmp
Thu Sep 21 21:18:39 2023 - WARN  - the remote password uses the default configuration.
Thu Sep 21 21:18:40 2023 - WARN  - the connect port using the default configuration
spawn scp -P 22 -r @:/tmp/rsa.txt /tmp
ssh: Could not resolve hostname : Name or service not known
scp: Connection closed
+ ret=255
+ test 255 -ne 0
+ LOG_ERROR 'Failed in remote SCP operation: 255'
+ message='Failed in remote SCP operation: 255'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote SCP operation: 255'
Thu Sep 21 21:18:40 2023 - ERROR - Failed in remote SCP operation: 255
+ return 255
++ cat /tmp/rsa.txt
++ awk -F rightrsasigkey= '{print $2}'
++ sed 's/^[ \t]*//g'
cat: /tmp/rsa.txt: No such file or directory
+ right_rsa=
+ P_SSH_CMD --cmd 'ifconfig  | grep netmask >/tmp/right_mask.txt' --node 2
+ python3 /root/mugen/libs/locallibs/ssh_cmd.py --cmd 'ifconfig  | grep netmask >/tmp/right_mask.txt' --node 2
Thu Sep 21 21:18:43 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_site_to_site_vpn.sh line 57'
+ message='oe_test_site_to_site_vpn.sh line 57'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_site_to_site_vpn.sh line 57'
Thu Sep 21 21:18:44 2023 - ERROR - oe_test_site_to_site_vpn.sh line 57
+ '[' 0 -eq 1 ']'
+ return 0
+ SSH_SCP @:/tmp/right_mask.txt /tmp
+ src=@:/tmp/right_mask.txt
+ dest=/tmp
+ remotepasswd='openEuler12#$'
+ connport=22
+ bash /root/mugen/libs/locallibs/sshscp.sh -p 'openEuler12#$' -o 22 -s @:/tmp/right_mask.txt -d /tmp
Thu Sep 21 21:18:44 2023 - WARN  - the remote password uses the default configuration.
Thu Sep 21 21:18:45 2023 - WARN  - the connect port using the default configuration
spawn scp -P 22 -r @:/tmp/right_mask.txt /tmp
ssh: Could not resolve hostname : Name or service not known
scp: Connection closed
+ ret=255
+ test 255 -ne 0
+ LOG_ERROR 'Failed in remote SCP operation: 255'
+ message='Failed in remote SCP operation: 255'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote SCP operation: 255'
Thu Sep 21 21:18:46 2023 - ERROR - Failed in remote SCP operation: 255
+ return 255
+ P_SSH_CMD --cmd 'ip -6 route show dev >/tmp/right6_mask.txt' --node 2
+ python3 /root/mugen/libs/locallibs/ssh_cmd.py --cmd 'ip -6 route show dev >/tmp/right6_mask.txt' --node 2
Thu Sep 21 21:18:48 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_site_to_site_vpn.sh line 60'
+ message='oe_test_site_to_site_vpn.sh line 60'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_site_to_site_vpn.sh line 60'
Thu Sep 21 21:18:49 2023 - ERROR - oe_test_site_to_site_vpn.sh line 60
+ '[' 0 -eq 1 ']'
+ return 0
+ SSH_SCP @:/tmp/right6_mask.txt /tmp
+ src=@:/tmp/right6_mask.txt
+ dest=/tmp
+ remotepasswd='openEuler12#$'
+ connport=22
+ bash /root/mugen/libs/locallibs/sshscp.sh -p 'openEuler12#$' -o 22 -s @:/tmp/right6_mask.txt -d /tmp
Thu Sep 21 21:18:49 2023 - WARN  - the remote password uses the default configuration.
Thu Sep 21 21:18:50 2023 - WARN  - the connect port using the default configuration
spawn scp -P 22 -r @:/tmp/right6_mask.txt /tmp
ssh: Could not resolve hostname : Name or service not known
scp: Connection closed
+ ret=255
+ test 255 -ne 0
+ LOG_ERROR 'Failed in remote SCP operation: 255'
+ message='Failed in remote SCP operation: 255'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote SCP operation: 255'
Thu Sep 21 21:18:51 2023 - ERROR - Failed in remote SCP operation: 255
+ return 255
++ awk '{print $4}'
++ cat /tmp/right_mask.txt
cat: /tmp/right_mask.txt: No such file or directory
+ right_mask=
++ cat /tmp/right6_mask.txt
++ awk '{print $1}'
cat: /tmp/right6_mask.txt: No such file or directory
+ right6_mask=
+ echo -e 'conn mysubnet\n     also=mytunnel\n     leftsubnet=255.255.0.0
255.255.255.0
255.0.0.0/24\n     rightsubnet=/24\n     
    auto=start\n\nconn mysubnet6\n     also=mytunnel\n     leftsubnet=\n     rightsubnet=\n     
    auto=start\n\n\nconn mytunnel\n    leftid=@west\n    left=127.0.0.1\n    leftrsasigkey=0sAwEAAcdalcYYecvYjDPVK2QB8w+6poWzRVRZP6++oV3TPqJHMNs7ePvaPbMCgmxMkTu8mVgmFBh3TidZQIgsP3TNJJCvqef7kMH1hRvuGO0QR55EW8GTrpz7dra8Somu7UNpH5PtrMxPw3rFnocMfApiQY7BJ3qEKDdNz2x7OmCsLyMtQD6wXOfKPLFEDInnELc+NvII1Mg1Re3F7QZLQjQbB0fZXrWMwiz3ONGEYqcyi1t9B2kBjvvpnbyfF03SjdHDnqZXvr8J+C7AVoktCPFx/qAAdEC1c3hq0m4Ilig8LMr3F4Z1rE4JN1UvFgxH3LMw2GagAEi5P88K3NlZJDnkG6+CzZFKdz0qBdUmq3N10yHkuQaw/41B3Lj6Wxn/rtUH5RutU368AY+R6xubTxzFouid+G0gVNjsRIwg8VGooCNo9PS1jn1CfeMPKszCTUS2Wlg5J3kBB1HI4F1K7XwVLiUKeNbWMGnb9FI5Wrn8uwlPa2lpNmgGJB+G2ZZKMUAmy00nHb9swEI8XBmdDNNLb15Vye7ENssV2uK0J777LXtJPKr7hLNECFtvyzdo0PEIUgGj0Ky1klj2PwUoT40zTaobU/UP+VU=\n    
    rightid=@east\n    right=\n    rightrsasigkey=\n    authby=rsasig'
+ SSH_SCP /etc/ipsec.d/my_site-to-site.conf @:/etc/ipsec.d/
+ src=/etc/ipsec.d/my_site-to-site.conf
+ dest=@:/etc/ipsec.d/
+ remotepasswd='openEuler12#$'
+ connport=22
+ bash /root/mugen/libs/locallibs/sshscp.sh -p 'openEuler12#$' -o 22 -s /etc/ipsec.d/my_site-to-site.conf -d @:/etc/ipsec.d/
Thu Sep 21 21:18:52 2023 - WARN  - the remote password uses the default configuration.
Thu Sep 21 21:18:52 2023 - WARN  - the connect port using the default configuration
spawn scp -P 22 -r /etc/ipsec.d/my_site-to-site.conf @:/etc/ipsec.d/
ssh: Could not resolve hostname : Name or service not known
scp: Connection closed
+ ret=255
+ test 255 -ne 0
+ LOG_ERROR 'Failed in remote SCP operation: 255'
+ message='Failed in remote SCP operation: 255'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Failed in remote SCP operation: 255'
Thu Sep 21 21:18:53 2023 - ERROR - Failed in remote SCP operation: 255
+ return 255
+ ipsec auto --add mysubnet
cannot load config '/etc/ipsec.conf': /etc/ipsec.d/my_site-to-site.conf:4: syntax error [255.255.255.0]
+ CHECK_RESULT 3 0 0 'add mysubnet failed'
+ actual_result=3
+ expect_result=0
+ mode=0
+ error_log='add mysubnet failed'
+ exit_mode=0
+ '[' -z 3 ']'
+ '[' 0 -eq 0 ']'
+ test 3x '!=' 0x
+ test -n 'add mysubnet failed'
+ LOG_ERROR 'add mysubnet failed'
+ message='add mysubnet failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'add mysubnet failed'
Thu Sep 21 21:18:54 2023 - ERROR - add mysubnet failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_site_to_site_vpn.sh line 71'
+ message='oe_test_site_to_site_vpn.sh line 71'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_site_to_site_vpn.sh line 71'
Thu Sep 21 21:18:55 2023 - ERROR - oe_test_site_to_site_vpn.sh line 71
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl restart ipsec
Job for ipsec.service failed because the control process exited with error code.
See "systemctl status ipsec.service" and "journalctl -xeu ipsec.service" for details.
+ ipsec setup start
Redirecting to: systemctl start ipsec.service
Job for ipsec.service failed because the control process exited with error code.
See "systemctl status ipsec.service" and "journalctl -xeu ipsec.service" for details.
+ P_SSH_CMD --cmd 'ipsec auto --add mysubnet;systemctl restart ipsec;ipsec setup start' --node 2
+ python3 /root/mugen/libs/locallibs/ssh_cmd.py --cmd 'ipsec auto --add mysubnet;systemctl restart ipsec;ipsec setup start' --node 2
Thu Sep 21 21:19:00 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ ipsec auto --up mysubnet
whack: Pluto is not running (no "/run/pluto/pluto.ctl")
+ CHECK_RESULT 33 0 0 'up mysubnet failed'
+ actual_result=33
+ expect_result=0
+ mode=0
+ error_log='up mysubnet failed'
+ exit_mode=0
+ '[' -z 33 ']'
+ '[' 0 -eq 0 ']'
+ test 33x '!=' 0x
+ test -n 'up mysubnet failed'
+ LOG_ERROR 'up mysubnet failed'
+ message='up mysubnet failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'up mysubnet failed'
Thu Sep 21 21:19:01 2023 - ERROR - up mysubnet failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_site_to_site_vpn.sh line 77'
+ message='oe_test_site_to_site_vpn.sh line 77'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_site_to_site_vpn.sh line 77'
Thu Sep 21 21:19:01 2023 - ERROR - oe_test_site_to_site_vpn.sh line 77
+ '[' 0 -eq 1 ']'
+ return 0
+ P_SSH_CMD --cmd 'ipsec auto --up mysubnet' --node 2
+ python3 /root/mugen/libs/locallibs/ssh_cmd.py --cmd 'ipsec auto --up mysubnet' --node 2
Thu Sep 21 21:19:04 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_site_to_site_vpn.sh line 79'
+ message='oe_test_site_to_site_vpn.sh line 79'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_site_to_site_vpn.sh line 79'
Thu Sep 21 21:19:04 2023 - ERROR - oe_test_site_to_site_vpn.sh line 79
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'Finish testcase execution.'
+ message='Finish testcase execution.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish testcase execution.'
Thu Sep 21 21:19:05 2023 - INFO  - Finish testcase execution.
+ CASE_RESULT 0
+ case_re=0
+ test -z 8
+ test 8 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Thu Sep 21 21:19:06 2023 - ERROR - failed to execute the case.
+ exit 8
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Thu Sep 21 21:19:06 2023 - INFO  - start environment cleanup.
+ systemctl stop ipsec
+ firewall-cmd --remove-service=ipsec
success
+ firewall-cmd --runtime-to-permanent
success
+ P_SSH_CMD --cmd 'systemctl stop ipsec;firewall-cmd --remove-service=ipsec;firewall-cmd --runtime-to-permanent' --node 2
+ python3 /root/mugen/libs/locallibs/ssh_cmd.py --cmd 'systemctl stop ipsec;firewall-cmd --remove-service=ipsec;firewall-cmd --runtime-to-permanent' --node 2
Thu Sep 21 21:19:19 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Thu Sep 21 21:19:20 2023 - WARN  - no thing to do.
+ return 0
+ DNF_REMOVE 2 'net-tools libreswan'
+ node=2
+ pkg_list='net-tools libreswan'
+ mode=0
+ [[ -z '' ]]
+ [[ -z net-tools libreswan ]]
+ '[' 0 -ne 0 ']'
+ '[' 2 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 2 --pkgs 'net-tools libreswan' --tempfile ''
Traceback (most recent call last):
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 192, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mugen/libs/locallibs/rpm_manage.py", line 153, in rpm_remove
    conn = ssh_cmd.pssh_conn(
           ^^^^^^^^^^^^^^^^^^
  File "/root/mugen/libs/locallibs/ssh_cmd.py", line 53, in pssh_conn
    conn.connect(ip, port, user, password, timeout=timeout)
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 377, in connect
    to_try = list(self._families_and_addresses(hostname, port))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/paramiko/client.py", line 202, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
+ '[' 0 -ne 0 ']'
+ rm -rf '/tmp/*.txt' /etc/ipsec.d/cert9.db /etc/ipsec.d/key4.db /etc/ipsec.d/my_site-to-site.conf /etc/ipsec.d/pkcs11.txt '/var/lib/ipsec/nss/*.db'
+ P_SSH_CMD --cmd 'rm -rf /tmp/*.txt /etc/ipsec.d/* /var/lib/ipsec/nss/*.db' --node 2
+ python3 /root/mugen/libs/locallibs/ssh_cmd.py --cmd 'rm -rf /tmp/*.txt /etc/ipsec.d/* /var/lib/ipsec/nss/*.db' --node 2
Thu Sep 21 21:19:25 2023 - ERROR - You need to check the environment configuration file to see if this node information exists.
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Thu Sep 21 21:19:26 2023 - INFO  - Finish environment cleanup!
