+ source ../common/common_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environmental preparation.'
+ message='Start environmental preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environmental preparation.'
Wed Sep 27 09:45:59 2023 - INFO  - Start environmental preparation.
++ hostname
+ host_name=openeuler-riscv64
+ hostname OE-TESTD
+ echo '127.0.0.1 TESTAD.LOCAL'
+ DNF_INSTALL 'samba-dc python3-samba-dc krb5-server'
+ pkgs='samba-dc python3-samba-dc krb5-server'
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs 'samba-dc python3-samba-dc krb5-server' --node 1 --tempfile ''
+ tmpfile2=/tmp/tmpxluvjn8n
+ '[' -z '' ']'
+ tmpfile=/tmp/tmpxluvjn8n
+ mv /etc/samba/smb.conf /etc/samba/smb.conf_bak
+ expect
spawn samba-tool domain provision --use-rfc2307 --interactive --function-level=2008_R2
Realm:  TESTAD.LOCAL
Domain [TESTAD]:  
Server Role (dc, member, standalone) [dc]:  
DNS backend (SAMBA_INTERNAL, BIND9_FLATFILE, BIND9_DLZ, NONE) [SAMBA_INTERNAL]:  
DNS forwarder IP address (write 'none' to disable forwarding) [10.0.2.3]:  
Administrator password: 
Retype password: 
[1;32mINFO 2023-09-27 09:47:09,666 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #2108: Looking up IPv4 addresses[0m
[1;33mWARNING 2023-09-27 09:47:09,672 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #2113: More than one IPv4 address found. Using 172.17.0.1[0m
[1;32mINFO 2023-09-27 09:47:09,674 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #2125: Looking up IPv6 addresses[0m
[1;33mWARNING 2023-09-27 09:47:09,678 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #2130: More than one IPv6 address found. Using fec0::ff9:a85c:c3c7:74ac[0m
[1;32mINFO 2023-09-27 09:47:12,674 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #2274: Setting up share.ldb[0m
[1;32mINFO 2023-09-27 09:47:12,820 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #2278: Setting up secrets.ldb[0m
[1;32mINFO 2023-09-27 09:47:12,946 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #2283: Setting up the registry[0m
[1;32mINFO 2023-09-27 09:47:13,324 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #2286: Setting up the privileges database[0m
[1;32mINFO 2023-09-27 09:47:13,547 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #2289: Setting up idmap db[0m
[1;32mINFO 2023-09-27 09:47:13,758 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #2296: Setting up SAM db[0m
[1;32mINFO 2023-09-27 09:47:13,822 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #880: Setting up sam.ldb partitions and settings[0m
[1;32mINFO 2023-09-27 09:47:13,831 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #892: Setting up sam.ldb rootDSE[0m
[1;32mINFO 2023-09-27 09:47:13,860 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #1305: Pre-loading the Samba 4 and AD schema[0m
Unable to determine the DomainSID, can not enforce uniqueness constraint on local domainSIDs

[1;32mINFO 2023-09-27 09:47:14,159 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #1383: Adding DomainDN: DC=testad,DC=local[0m
[1;32mINFO 2023-09-27 09:47:14,286 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #1415: Adding configuration container[0m
[1;32mINFO 2023-09-27 09:47:14,383 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #1430: Setting up sam.ldb schema[0m
[1;32mINFO 2023-09-27 09:47:35,287 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #1448: Setting up sam.ldb configuration data[0m
[1;32mINFO 2023-09-27 09:47:36,477 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #1489: Setting up display specifiers[0m
[1;32mINFO 2023-09-27 09:47:50,821 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #1497: Modifying display specifiers and extended rights[0m
[1;32mINFO 2023-09-27 09:47:51,047 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #1504: Adding users container[0m
[1;32mINFO 2023-09-27 09:47:51,056 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #1510: Modifying users container[0m
[1;32mINFO 2023-09-27 09:47:51,060 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #1513: Adding computers container[0m
[1;32mINFO 2023-09-27 09:47:51,068 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #1519: Modifying computers container[0m
[1;32mINFO 2023-09-27 09:47:51,073 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #1523: Setting up sam.ldb data[0m
[1;32mINFO 2023-09-27 09:47:52,012 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #1553: Setting up well known security principals[0m
[1;32mINFO 2023-09-27 09:47:52,273 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #1567: Setting up sam.ldb users and groups[0m
[1;32mINFO 2023-09-27 09:47:52,884 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #1575: Setting up self join[0m
Repacking database from v1 to v2 format (first record CN=Server-Reference,CN=Schema,CN=Configuration,DC=testad,DC=local)
Repack: re-packed 10000 records so far
Repacking database from v1 to v2 format (first record CN=group-Display,CN=40B,CN=DisplaySpecifiers,CN=Configuration,DC=testad,DC=local)
Repacking database from v1 to v2 format (first record CN=8ddf6913-1c7b-4c59-a5af-b9ca3b3d2c4c,CN=Operations,CN=DomainUpdates,CN=System,DC=testad,DC=local)
[1;32mINFO 2023-09-27 09:48:03,522 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/sambadns.py #1198: Adding DNS accounts[0m
[1;32mINFO 2023-09-27 09:48:03,697 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/sambadns.py #1232: Creating CN=MicrosoftDNS,CN=System,DC=testad,DC=local[0m
[1;32mINFO 2023-09-27 09:48:03,869 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/sambadns.py #1245: Creating DomainDnsZones and ForestDnsZones partitions[0m
[1;32mINFO 2023-09-27 09:48:04,229 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/sambadns.py #1250: Populating DomainDnsZones and ForestDnsZones partitions[0m
Repacking database from v1 to v2 format (first record DC=@,DC=testad.local,CN=MicrosoftDNS,DC=DomainDnsZones,DC=testad,DC=local)
Repacking database from v1 to v2 format (first record DC=gc,DC=_msdcs.testad.local,CN=MicrosoftDNS,DC=ForestDnsZones,DC=testad,DC=local)
[1;32mINFO 2023-09-27 09:48:05,786 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #2012: Setting up sam.ldb rootDSE marking as synchronized[0m
[1;32mINFO 2023-09-27 09:48:05,813 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #2017: Fixing provision GUIDs[0m
[1;32mINFO 2023-09-27 09:48:14,988 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #2342: The Kerberos KDC configuration for Samba AD is located at /var/lib/samba/private/kdc.conf[0m
[1;32mINFO 2023-09-27 09:48:14,991 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #2348: A Kerberos configuration suitable for Samba AD has been generated at /var/lib/samba/private/krb5.conf[0m
[1;32mINFO 2023-09-27 09:48:14,992 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #2350: Merge the contents of this file with your system krb5.conf or replace it with this one. Do not create a symlink![0m
[1;32mINFO 2023-09-27 09:48:15,259 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #2082: Setting up fake yp server settings[0m
[1;32mINFO 2023-09-27 09:48:15,784 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #487: Once the above files are installed, your Samba AD server will be ready to use[0m
[1;32mINFO 2023-09-27 09:48:15,785 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #492: Server Role:           active directory domain controller[0m
[1;32mINFO 2023-09-27 09:48:15,786 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #493: Hostname:              OE-TESTD[0m
[1;32mINFO 2023-09-27 09:48:15,786 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #494: NetBIOS Domain:        TESTAD[0m
[1;32mINFO 2023-09-27 09:48:15,787 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #495: DNS Domain:            testad.local[0m
[1;32mINFO 2023-09-27 09:48:15,787 pid:2182 /usr/lib64/python3.11/site-packages/samba/provision/__init__.py #496: DOMAIN SID:            S-1-5-21-3575044035-1937889938-3966372226[0m
+ mv /etc/krb5.conf /etc/krb5.bak
+ rm -rf /etc/krb5.conf
+ cp -raf /var/lib/samba/private/krb5.conf /etc/
+ systemctl stop firewalld
+ sed -i s/nameserver/#nameserver/ /etc/resolv.conf
+ echo 'nameserver 127.0.0.1'
+ flag=false
++ getenforce
++ grep Enforcing
+ '[' ']'
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Wed Sep 27 09:48:17 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start testing...'
+ message='Start testing...'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start testing...'
Wed Sep 27 09:48:17 2023 - INFO  - Start testing...
+ test_execution samba.service
+ service=samba.service
++ date '+%Y-%m-%d %T'
+ log_time='2023-09-27 09:48:17'
+ test_restart samba.service
+ service=samba.service
+ systemctl restart samba.service
+ CHECK_RESULT 0 0 0 'samba.service restart failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='samba.service restart failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status samba.service
+ grep 'Active: active'
     Active: active (running) since Wed 2023-09-27 09:48:21 CST; 5s ago
+ CHECK_RESULT 0 0 0 'samba.service restart failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='samba.service restart failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl stop samba.service
+ CHECK_RESULT 0 0 0 'samba.service stop failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='samba.service stop failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status samba.service
+ grep 'Active: inactive'
+ CHECK_RESULT 1 0 0 'samba.service stop failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='samba.service stop failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'samba.service stop failed'
+ LOG_ERROR 'samba.service stop failed'
+ message='samba.service stop failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'samba.service stop failed'
Wed Sep 27 09:48:40 2023 - ERROR - samba.service stop failed
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 42'
+ message='../common/common_lib.sh line 42'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 42'
Wed Sep 27 09:48:41 2023 - ERROR - ../common/common_lib.sh line 42
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl start samba.service
+ CHECK_RESULT 0 0 0 'samba.service start failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='samba.service start failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ SLEEP_WAIT 5
+ wait_time=5
+ cmd=
+ mode=1
+ python3 /root/mugen/libs/locallibs/sleep_wait.py --time 5 --cmd '' --mode 1
+ systemctl status samba.service
+ grep 'Active: active'
     Active: active (running) since Wed 2023-09-27 09:48:44 CST; 5s ago
+ CHECK_RESULT 0 0 0 'samba.service start failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='samba.service start failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ test_enabled samba.service
+ service=samba.service
++ systemctl is-enabled samba.service
+ state=disabled
+ '[' disabled == enabled ']'
+ '[' disabled == disabled ']'
++ systemctl enable samba.service
++ grep 'Created symlink'
++ awk '{print $3}'
+ symlink_file=/etc/systemd/system/multi-user.target.wants/samba.service
+ find /etc/systemd/system/multi-user.target.wants/samba.service
/etc/systemd/system/multi-user.target.wants/samba.service
+ CHECK_RESULT 0 0 0 'samba.service enable failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='samba.service enable failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl disable samba.service
Removed "/etc/systemd/system/multi-user.target.wants/samba.service".
+ find /etc/systemd/system/multi-user.target.wants/samba.service
find: ‘/etc/systemd/system/multi-user.target.wants/samba.service’: No such file or directory
+ CHECK_RESULT 1 0 1 'samba.service disable failed'
+ actual_result=1
+ expect_result=0
+ mode=1
+ error_log='samba.service disable failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 1 -eq 0 ']'
+ test 1x == 0x
+ return 0
+ journalctl --since '2023-09-27 09:48:17' -u samba.service
+ grep -i 'fail\|error'
+ grep -v -i 'DEBUG\|INFO\|WARNING'
Sep 27 09:48:34 OE-TESTD systemd[1]: samba.service: Failed with result 'exit-code'.
Sep 27 09:48:52 OE-TESTD samba[2316]:   gssapi_check_packet(hdr_signing=0,sig_size=28,data=121,pdu=121) failed: NT_STATUS_ACCESS_DENIED
Sep 27 09:48:52 OE-TESTD samba[2314]:   /usr/sbin/samba_dnsupdate: ; TSIG error with server: tsig indicates error
Sep 27 09:48:52 OE-TESTD samba[2314]:   /usr/sbin/samba_dnsupdate: update failed: NOTAUTH(BADSIG)
Sep 27 09:48:53 OE-TESTD samba[2316]:   gssapi_check_packet(hdr_signing=0,sig_size=28,data=133,pdu=133) failed: NT_STATUS_ACCESS_DENIED
Sep 27 09:48:53 OE-TESTD samba[2314]:   /usr/sbin/samba_dnsupdate: ; TSIG error with server: tsig indicates error
Sep 27 09:48:53 OE-TESTD samba[2314]:   /usr/sbin/samba_dnsupdate: update failed: NOTAUTH(BADSIG)
Sep 27 09:48:54 OE-TESTD samba[2316]:   gssapi_check_packet(hdr_signing=0,sig_size=28,data=112,pdu=112) failed: NT_STATUS_ACCESS_DENIED
Sep 27 09:48:54 OE-TESTD samba[2314]:   /usr/sbin/samba_dnsupdate: ; TSIG error with server: tsig indicates error
Sep 27 09:48:54 OE-TESTD samba[2314]:   /usr/sbin/samba_dnsupdate: update failed: NOTAUTH(BADSIG)
Sep 27 09:48:54 OE-TESTD samba[2316]:   gssapi_check_packet(hdr_signing=0,sig_size=28,data=124,pdu=124) failed: NT_STATUS_ACCESS_DENIED
Sep 27 09:48:54 OE-TESTD samba[2314]:   /usr/sbin/samba_dnsupdate: ; TSIG error with server: tsig indicates error
Sep 27 09:48:54 OE-TESTD samba[2314]:   /usr/sbin/samba_dnsupdate: update failed: NOTAUTH(BADSIG)
Sep 27 09:48:55 OE-TESTD samba[2316]:   gssapi_check_packet(hdr_signing=0,sig_size=28,data=122,pdu=122) failed: NT_STATUS_ACCESS_DENIED
Sep 27 09:48:55 OE-TESTD samba[2314]:   /usr/sbin/samba_dnsupdate: ; TSIG error with server: tsig indicates error
Sep 27 09:48:55 OE-TESTD samba[2314]:   /usr/sbin/samba_dnsupdate: update failed: NOTAUTH(BADSIG)
Sep 27 09:48:55 OE-TESTD samba[2316]:   gssapi_check_packet(hdr_signing=0,sig_size=28,data=134,pdu=134) failed: NT_STATUS_ACCESS_DENIED
Sep 27 09:48:55 OE-TESTD samba[2314]:   /usr/sbin/samba_dnsupdate: ; TSIG error with server: tsig indicates error
Sep 27 09:48:55 OE-TESTD samba[2314]:   /usr/sbin/samba_dnsupdate: update failed: NOTAUTH(BADSIG)
Sep 27 09:48:56 OE-TESTD samba[2316]:   gssapi_check_packet(hdr_signing=0,sig_size=28,data=127,pdu=127) failed: NT_STATUS_ACCESS_DENIED
Sep 27 09:48:56 OE-TESTD samba[2314]:   /usr/sbin/samba_dnsupdate: ; TSIG error with server: tsig indicates error
Sep 27 09:48:56 OE-TESTD samba[2314]:   /usr/sbin/samba_dnsupdate: update failed: NOTAUTH(BADSIG)
Sep 27 09:48:56 OE-TESTD samba[2316]:   gssapi_check_packet(hdr_signing=0,sig_size=28,data=139,pdu=139) failed: NT_STATUS_ACCESS_DENIED
Sep 27 09:48:56 OE-TESTD samba[2314]:   /usr/sbin/samba_dnsupdate: ; TSIG error with server: tsig indicates error
Sep 27 09:48:56 OE-TESTD samba[2314]:   /usr/sbin/samba_dnsupdate: update failed: NOTAUTH(BADSIG)
Sep 27 09:48:57 OE-TESTD samba[2316]:   gssapi_check_packet(hdr_signing=0,sig_size=28,data=127,pdu=127) failed: NT_STATUS_ACCESS_DENIED
Sep 27 09:48:57 OE-TESTD samba[2314]:   /usr/sbin/samba_dnsupdate: ; TSIG error with server: tsig indicates error
Sep 27 09:48:57 OE-TESTD samba[2314]:   /usr/sbin/samba_dnsupdate: update failed: NOTAUTH(BADSIG)
+ CHECK_RESULT 0 0 1 'There is an error message for the log of samba.service'
+ actual_result=0
+ expect_result=0
+ mode=1
+ error_log='There is an error message for the log of samba.service'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 1 -eq 0 ']'
+ test 0x == 0x
+ test -n 'There is an error message for the log of samba.service'
+ LOG_ERROR 'There is an error message for the log of samba.service'
+ message='There is an error message for the log of samba.service'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'There is an error message for the log of samba.service'
Wed Sep 27 09:48:58 2023 - ERROR - There is an error message for the log of samba.service
+ (( exec_result++ ))
+ LOG_ERROR '../common/common_lib.sh line 28'
+ message='../common/common_lib.sh line 28'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message '../common/common_lib.sh line 28'
Wed Sep 27 09:48:58 2023 - ERROR - ../common/common_lib.sh line 28
+ '[' 0 -eq 1 ']'
+ return 0
+ sed -i 's\/usr/sbin/samba --foreground --no-process-group $SAMBAOPTIONS\/usr/sbin/samba --foreground --no-process-group $SAMBAOPTIONS -d 10\' /usr/lib/systemd/system/samba.service
+ systemctl daemon-reload
+ systemctl reload samba.service
+ CHECK_RESULT 0 0 0 'samba.service reload failed'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='samba.service reload failed'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ systemctl status samba.service
+ grep 'Active: active'
     Active: active (running) since Wed 2023-09-27 09:48:44 CST; 17s ago
+ CHECK_RESULT 0 0 0 'samba.service reload causes the service status to change'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='samba.service reload causes the service status to change'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'Finish test!'
+ message='Finish test!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish test!'
Wed Sep 27 09:49:02 2023 - INFO  - Finish test!
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Sep 27 09:49:03 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Wed Sep 27 09:49:03 2023 - INFO  - start environment cleanup.
+ sed -i 's\/usr/sbin/samba --foreground --no-process-group $SAMBAOPTIONS -d\/usr/sbin/samba --foreground --no-process-group $SAMBAOPTIONS\' /usr/lib/systemd/system/samba.service
+ systemctl daemon-reload
+ systemctl reload samba.service
+ systemctl stop samba.service
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z /tmp/tmpxluvjn8n ]]
+ '[' 0 -ne 0 ']'
+ '[' 1 == 0 ']'
+ python3 /root/mugen/libs/locallibs/rpm_manage.py remove --node 1 --pkgs '' --tempfile /tmp/tmpxluvjn8n
+ '[' 0 -ne 0 ']'
+ sed -i '/nameserver 127.0.0.1/d' /etc/resolv.conf
+ sed -i s/#nameserver/nameserver/ /etc/resolv.conf
+ hostname openeuler-riscv64
+ sed -i /TESTAD/d /etc/hosts
+ systemctl start firewalld
+ '[' false = true ']'
+ rm -rf /etc/samba/smb.conf /var/lib/samba/private/dns_update_cache /var/lib/samba/private/dns_update_list /var/lib/samba/private/encrypted_secrets.key /var/lib/samba/private/hklm.ldb /var/lib/samba/private/idmap.ldb /var/lib/samba/private/kdc.conf /var/lib/samba/private/krb5.conf /var/lib/samba/private/ldapi /var/lib/samba/private/ldap_priv /var/lib/samba/private/msg.sock /var/lib/samba/private/netlogon_creds_cli.tdb /var/lib/samba/private/privilege.ldb /var/lib/samba/private/sam.ldb /var/lib/samba/private/sam.ldb.d /var/lib/samba/private/schannel_store.tdb /var/lib/samba/private/secrets.keytab /var/lib/samba/private/secrets.ldb /var/lib/samba/private/secrets.tdb /var/lib/samba/private/share.ldb /var/lib/samba/private/smbd.tmp /var/lib/samba/private/spn_update_list /var/lib/samba/private/tls /var/lib/samba/sysvol/testad.local
+ mv -f /etc/krb5.bak /etc/krb5.conf
+ mv -f /etc/samba/smb.conf_bak /etc/samba/smb.conf
+ LOG_INFO 'Finish environment cleanup!'
+ message='Finish environment cleanup!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup!'
Wed Sep 27 09:49:32 2023 - INFO  - Finish environment cleanup!
