+ source ../common/storage_disk_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Wed Sep 13 13:43:16 2023 - INFO  - Start environment preparation.
+ check_free_disk
++ TEST_DISK
++ id=1
++ python3 /root/mugen/libs/locallibs/get_test_device.py --device disk --node 1
+ disks='vdb vdc vdd vde'
+ disk_list=($disks)
+ local_disk=vdb
+ local_disk1=vdc
+ local_disk2=vdd
+ local_disk3=vde
+ pvcreate -y /dev/vdc
Wed Sep 13 14:13:14 2023 - ERROR - Timeout : Command 'bash -x oe_test_storage_lvm_set_lvconvert_raid1.sh' timed out after 1799.9995555000005 seconds
  Wiping xfs signature on /dev/vdc.
  Physical volume "/dev/vdc" successfully created.
++ post_test
++ LOG_INFO 'start environment cleanup.'
++ message='start environment cleanup.'
++ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Wed Sep 13 16:15:13 2023 - INFO  - start environment cleanup.
++ lvremove -y openeulertest/test
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
++ vgremove -y openeulertest
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
++ pvremove /dev/vdc /dev/vdb
  No PV found on device /dev/vdc.
  No PV found on device /dev/vdb.
++ LOG_INFO 'Finish environment cleanup.'
++ message='Finish environment cleanup.'
++ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Wed Sep 13 16:15:16 2023 - INFO  - Finish environment cleanup.
+ vgcreate openeulertest /dev/vdc -y
  A volume group called openeulertest already exists.
+ vgextend openeulertest /dev/vdb -y
  Physical volume '/dev/vdb' is already in volume group 'openeulertest'
  Unable to add physical volume '/dev/vdb' to volume group 'openeulertest'
  /dev/vdb: physical volume not initialized.
+ lvcreate -m1 -n test -L 1G openeulertest --type mirror -y
  WARNING: PV /dev/vde in VG openeulertest is missing the used flag in PV header.
  Logical Volume "test" already exists in volume group "openeulertest"
+ LOG_INFO 'Environmental preparation is over.'
+ message='Environmental preparation is over.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Environmental preparation is over.'
Wed Sep 13 16:15:22 2023 - INFO  - Environmental preparation is over.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start executing testcase!'
+ message='Start executing testcase!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start executing testcase!'
Wed Sep 13 16:15:25 2023 - INFO  - Start executing testcase!
+ lvs -a -o name,copy_percent,devices openeulertest
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_set_lvconvert_raid1.sh line 33'
+ message='oe_test_storage_lvm_set_lvconvert_raid1.sh line 33'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_set_lvconvert_raid1.sh line 33'
Wed Sep 13 16:15:27 2023 - ERROR - oe_test_storage_lvm_set_lvconvert_raid1.sh line 33
+ '[' 0 -eq 1 ']'
+ return 0
+ lvconvert -m0 openeulertest/test -y
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_set_lvconvert_raid1.sh line 35'
+ message='oe_test_storage_lvm_set_lvconvert_raid1.sh line 35'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_set_lvconvert_raid1.sh line 35'
Wed Sep 13 16:15:30 2023 - ERROR - oe_test_storage_lvm_set_lvconvert_raid1.sh line 35
+ '[' 0 -eq 1 ']'
+ return 0
+ lvs -a -o name,copy_percent,devices openeulertest
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ CHECK_RESULT 5
+ actual_result=5
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 5 ']'
+ '[' 0 -eq 0 ']'
+ test 5x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_storage_lvm_set_lvconvert_raid1.sh line 37'
+ message='oe_test_storage_lvm_set_lvconvert_raid1.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_storage_lvm_set_lvconvert_raid1.sh line 37'
Wed Sep 13 16:15:33 2023 - ERROR - oe_test_storage_lvm_set_lvconvert_raid1.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End of testcase execution!'
+ message='End of testcase execution!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of testcase execution!'
Wed Sep 13 16:15:34 2023 - INFO  - End of testcase execution!
+ CASE_RESULT 0
+ case_re=0
+ test -z 3
+ test 3 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Wed Sep 13 16:15:35 2023 - ERROR - failed to execute the case.
+ exit 3
+ post_test
+ LOG_INFO 'start environment cleanup.'
+ message='start environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'start environment cleanup.'
Wed Sep 13 16:15:35 2023 - INFO  - start environment cleanup.
+ lvremove -y openeulertest/test
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ vgremove -y openeulertest
  Volume group "openeulertest" not found
  Cannot process volume group openeulertest
+ pvremove /dev/vdc /dev/vdb
  No PV found on device /dev/vdc.
  No PV found on device /dev/vdb.
+ LOG_INFO 'Finish environment cleanup.'
+ message='Finish environment cleanup.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish environment cleanup.'
Wed Sep 13 16:15:36 2023 - INFO  - Finish environment cleanup.
